### ISSUE TITLE
Add http link remote backend

### ISSUE THREAD

**Issue by rominf** [rstojnic/lazydata#6]
I have a project https://github.com/rominf/profanityfilter that could benefit from lazydata. I think it would be cool to move badword dictionaries out of repository and track them alongside hunspell dictionaries with lazydata. The problem is that I want these files to be accessible by end users, that means, I don't want them to be stored in AWS. Instead, I would like them downloaded by http link.

**Comment by rstojnic** [comment]
Agreed, this is very high on my priority list!

**Comment by rominf** [comment]
PR #13 closes this.
